### ISSUE TITLE
onedrive的几个webdav都挂载不上

### ISSUE THREAD

**Issue by handbye** [ChirmyRam/ChirmyRam-OneDrive-Repository#11]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/26617058/209675458-026d363b-cf1f-4d34-8602-edb48a9a914f.png">
除了这个工具也试了infuse等，都不行。好像认证有问题

**Comment by ChirmyRam** [comment]
我在批量搬运这一节中已说明OneDrive官方的webdav仅有少数软件支持，而且我这是rclone加密后的，所以只能放在rclone用。你要挂载webdav就直接用我自建的alist的webdav。

**Comment by handbye** [comment]
好的，明白了，谢谢
