### ISSUE TITLE
关于批量搬运

### ISSUE THREAD

**Issue by auspicious-youth** [ChirmyRam/ChirmyRam-OneDrive-Repository#14]
你好，想问下批量搬运的话，有无服务器推荐（大概价格也说下），用rclone转到onedrive，传输速度大概多少。
我本地传输速度平均下来不到1Mbps，太慢了

**Comment by ChirmyRam** [comment]
如果从我这里批量转存得看运气，天天爆满。其他域一般能长期维持10MB/s~20MB/s，热门的服务器是buyvm的1G1C机子，G口共享宽带，每月支付宝结算10块。

**Comment by ChirmyRam** [comment]
原分享链接已经失效了。

**Comment by ChirmyRam** [comment]
我见过到有人通过cloudreve配合aria2的方式手动离线速度比较快，不过需要较大的储存空间，你可以试试

**Comment by auspicious-youth** [comment]
离线下载到本地硬盘，然后再从本地硬盘上传到自己的onedrive吗？
我试试

**Comment by ChirmyRam** [comment]
cloudreve对接aria2后可自动上传到OneDrive并删除本地文件。

**Comment by auspicious-youth** [comment]
我现在把cloudreve和aria2都搭建好了，有一个问题就是怎么样通过【新建离线下载任务】下载到[https://qimilan-my.sharepoint.com/personal/4k1_2_chirmyram_top/Documents/](url)里面的文件，
![image](https://user-images.githubusercontent.com/94423990/215955503-6a177bd5-0674-49bd-ab3f-4a5825887160.png)
![image](https://user-images.githubusercontent.com/94423990/215955578-447950fa-e48e-4844-b33d-1b28d115d0c6.png)

**Comment by ChirmyRam** [comment]
下载alist直链

**Comment by auspicious-youth** [comment]
[https://al.chirmyram.com/d/tlv1/%E6%B3%B0%E5%89%A7/%E7%A6%81%E5%BF%8C%E5%A5%B3%E5%AD%A9/%E7%A6%81%E5%BF%8C%E5%A5%B3%E5%AD%A9%E7%AC%AC%E4%B8%80%E5%AD%A3/%E7%A6%81%E5%BF%8C%E5%A5%B3%E5%AD%A9%20-%20S01E01%20-%20%E4%B8%91%E9%99%8B%E7%9A%84%E7%9C%9F%E7%9B%B8.mkv](url)
直接创建任务就失败了，先用的tlv里面的泰剧测试的
![image](https://user-images.githubusercontent.com/94423990/215961068-c05191f4-ac65-41db-8f68-14c971f75c9b.png)
![image](https://user-images.githubusercontent.com/94423990/215960994-2df7a48f-c8ac-43f1-ab1a-0a6f31cd7bf3.png)

**Comment by ChirmyRam** [comment]
电视剧API炸了，4K的访问量相对较少。

**Comment by auspicious-youth** [comment]
![image](https://user-images.githubusercontent.com/94423990/215962450-b6e22437-f0b9-4e98-aee6-b19483c94afd.png)
都不行，我再看看

**Comment by ChirmyRam** [comment]
4K那个明明是你容量不足，检查下cloudreve控制面板给当前账号有没有分配足够容量，不是本地有多少空间账号就有多少空间。

**Comment by auspicious-youth** [comment]
好像可以了，我再试下，谢谢

**Comment by auspicious-youth** [comment]
用直链下载偶尔会出现67字节的同名文件，这是因为alist不稳定的原因吗

**Comment by ChirmyRam** [comment]
你打开这个文件看看内容，就是OneDrive炸了的报错

**Comment by auspicious-youth** [comment]
好吧，确实是炸了的话，也没办法了
