### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by villain2022** [ChirmyRam/ChirmyRam-OneDrive-Repository#16]
大佬您好..刚看过你的站.发现特别好..请问下您有古籍或者风水类的资源吗

**Comment by ChirmyRam** [comment]
我没有特别留意这方面的内容，见到就搬，你自己翻一下看看。

**Comment by villain2022** [comment]
我翻了没看到，想着您能搜一下吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月12日 09:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ChirmyRam/ChirmyRam-OneDrive-Repository] 您好 (Issue #16) |

我没有特别留意这方面的内容，见到就搬，你自己翻一下看看。

**Comment by ChirmyRam** [comment]
文件太多了，建立搜索索引很麻烦，现在只能手动翻。

**Comment by ChirmyRam** [comment]
现在已启用搜索功能。
