### ISSUE TITLE
请教E5 developer订阅怎么上传单文件大于2g

### ISSUE THREAD

**Issue by cairs00** [ChirmyRam/ChirmyRam-OneDrive-Repository#18]
如题,我看你盘里都很多大于2g的单文件,请问是如何传上去的呢？我自己申请的E5传不上大于2g的文件。谢谢

**Comment by ChirmyRam** [comment]
你怎么上传的？提示什么？

**Comment by cairs00** [comment]
用的rclone copy 提示Failed to copy: 413 Request Entity Too Large

**Comment by ChirmyRam** [comment]
你从哪copy到E5？直接网页上传都行。

**Comment by cairs00** [comment]
从aliyun-webdav和从本地磁盘都提示一样的错误

**Comment by ChirmyRam** [comment]
你去谷歌搜一下这个报错，我基本都是从OneDrive到OneDrive，很少碰到这种报错。

**Comment by cairs00** [comment]
谢谢回复,我也尝试了从你的onedrive 拷贝一样是413错误

**Comment by ChirmyRam** [comment]
你可以尝试用air explore挂载webdav

**Comment by cairs00** [comment]
好的谢谢,这个好像没有linux端,我都是挂vps或者软路由端同步

**Comment by cairs00** [comment]
air explorer我试了是可以传大于2g,谢谢
