### ISSUE TITLE
Cannot copy content to local storage via WebDAV

### ISSUE THREAD

**Issue by everwisher** [ChirmyRam/ChirmyRam-OneDrive-Repository#26]
<img width="627" alt="Snipaste_20240214_133153" src="https://github.com/ChirmyRam/ChirmyRam-OneDrive-Repository/assets/12667683/973f4fd2-0dfd-4f62-9f29-6e058e5756c6">

After mounting "https://alist:alist@al.chirmyram.com/dav" successfully on both Synology File Station and macOS Finder via WebDAV protocol, I can browse the content in your Alist site. However, I ended up being unable to copy anything to my local storage. Please help.

**Comment by ChirmyRam** [comment]
I don't have an Apple device to try this, maybe you're better off downloading it from the website or trying something else.
