### ISSUE TITLE
webdav登录失败

### ISSUE THREAD

**Issue by jaychoucc** [ChirmyRam/ChirmyRam-OneDrive-Repository#30]
大佬你好，
配置的webdav登录方式
url = https://al.chirmyram.com/dav/
user = alist
pass = kCJQSyuVJDmwgI0BM60Mtum8VGnI

显示账号登陆失败，访客账户的密码不正确吗？

**Comment by jaychoucc** [comment]
我用的alist

**Comment by jaychoucc** [comment]
只能用Rclone吗？密码是Rclone加密后的吧？

**Comment by jaychoucc** [comment]
已解决

**Comment by ChirmyRam** [comment]
webdav挂载的密码也是alist，我修改的时候不小心删掉了，明天再加回来
