### ISSUE TITLE
牛津高阶第10版有个文件无法下载

### ISSUE THREAD

**Issue by xuchengpeng** [ChirmyRam/ChirmyRam-OneDrive-Repository#34]
[牛津高阶（第10版 英汉双解） V2_0.1.mdd](https://al.chirmyram.com/rep/Doc/%E6%AC%A7%E8%B7%AF%E8%AF%8D%E5%85%B8%E5%BA%93/%E7%89%9B%E6%B4%A5%E9%AB%98%E9%98%B6%EF%BC%88%E7%AC%AC10%E7%89%88%20%E8%8B%B1%E6%B1%89%E5%8F%8C%E8%A7%A3%EF%BC%89V2.0/%E7%89%9B%E6%B4%A5%E9%AB%98%E9%98%B6%EF%BC%88%E7%AC%AC10%E7%89%88%20%E8%8B%B1%E6%B1%89%E5%8F%8C%E8%A7%A3%EF%BC%89%20V2_0.1.mdd)

{"code":500,"msg":"failed link: failed get link: The request has been throttled"}

**Comment by ChirmyRam** [comment]
等待一段时间再下。
