### ISSUE TITLE
太牛逼了吧...

### ISSUE THREAD

**Issue by sss1243a789** [ChirmyRam/ChirmyRam-OneDrive-Repository#7]
简直无敌...震惊之情无以言表

**Comment by ChirmyRam** [comment]
刚刚被微软制裁了，OneDrive将在明年1月禁用，我现在正在想办法抢救。

**Comment by wsshub** [comment]
> 刚刚被微软制裁了，OneDrive将在明年1月禁用，我现在正在想办法抢救。
真的吗，今天刚发现你的仓库，明年1月e5的OneDrive都不能用了吗

**Comment by ChirmyRam** [comment]
> > 真的吗，今天刚发现你的仓库，明年1月e5的OneDrive都不能用了吗

只是我的OneDrive被禁用，文件变成了只读，而且是前六个盘，后面三个盘目前功能正常

**Comment by wsshub** [comment]
> > > 真的吗，今天刚发现你的仓库，明年1月e5的OneDrive都不能用了吗
> 
> 只是我的OneDrive被禁用，文件变成了只读，而且是前六个盘，后面三个盘目前功能正常

哦哦，辛苦大佬了，大佬知不知道emby，可以自动削刮电影电视剧元数据，如果用emby配合你的仓库可以搭一个视频站，但是还有一些问题，有没有兴趣加个Q(2729950578)聊一下

**Comment by ChirmyRam** [comment]
> 哦哦，辛苦大佬了，大佬知不知道emby，可以自动削刮电影电视剧元数据，如果用emby配合你的仓库可以搭一个视频站，但是还有一些问题，有没有兴趣加个Q(2729950578)聊一下

曾经折腾过emby，不过眼下最重要的是我先看看能否解决OneDrive的问题，否则一切都是白费功夫。

**Comment by wsshub** [comment]
> > 哦哦，辛苦大佬了，大佬知不知道emby，可以自动削刮电影电视剧元数据，如果用emby配合你的仓库可以搭一个视频站，但是还有一些问题，有没有兴趣加个Q(2729950578)聊一下
> 
> 曾经折腾过emby，不过眼下最重要的是我先看看能否解决OneDrive的问题，否则一切都是白费功夫。
目前你仓库里电影的命名格式(中文名.英文名)emby识别不了，可以写个脚本，批量重命名为[中文名].英文名就可以了

**Comment by ChirmyRam** [comment]
> > 真的吗，今天刚发现你的仓库，明年1月e5的OneDrive都不能用了吗

已救回。

**Comment by Sansui233** [comment]
我也刚看到，一个人整理那么多资源，给您跪了……巨硬封号搬东西还挺麻烦的……
