### ISSUE TITLE
建议大佬把电影名改为[中文名].英文名的格式，方便emby削刮

### ISSUE THREAD

**Issue by wsshub** [ChirmyRam/ChirmyRam-OneDrive-Repository#8]
中文名.英文名的格式emby削刮不了，建议改成[中文名].英文名的格式，我用python写了个[脚本](https://github.com/wsshub/emby_plus/blob/main/rename.py)，通过webdav挂载到本地后，输入文件夹path可以自动重命名。

**Comment by ChirmyRam** [comment]
明年1月份的时候我才会考虑，当务之急是在和客服斗智斗勇并且搬运数据。

**Comment by wsshub** [comment]
> 明年1月份的时候我才会考虑，当务之急是在和客服斗智斗勇并且搬运数据。

祝大佬成功

**Comment by ChirmyRam** [comment]
> 中文名.英文名的格式emby削刮不了，建议改成[中文名].英文名的格式，我用python写了个[脚本](https://github.com/wsshub/emby_plus/blob/main/rename.py)，通过webdav挂载到本地后，输入文件夹path可以自动重命名。

正在着手准备这件事，我先复制一部分电影进行测试，最近比较忙，可能进度缓慢，我有疑问的话会慢慢与你讨论。

**Comment by sss1243a789** [comment]
漫威电影突然全删了啊...为什么啊

**Comment by ChirmyRam** [comment]
> 漫威电影突然全删了啊...为什么啊

正在补回去，本来尝试重命名格式的，结果搞乱了，索性删掉后直接从备份的号里面再迁移过来，预计还要两天左右恢复。

**Comment by ChirmyRam** [comment]
> 漫威电影突然全删了啊...为什么啊

已恢复。

**Comment by ChirmyRam** [comment]
已完成改名。

**Comment by hjfrank1991** [comment]
nova 貌似对这种命名的挂海报 不太行
