### ISSUE TITLE
大佬想问一下，E5扩容25T

### ISSUE THREAD

**Issue by mengguyi** [ChirmyRam/ChirmyRam-OneDrive-Repository#9]
大佬想问一下，E5现在还能扩容25T吗，我看你的盘是25T的以前听你说过能扩，不知道现在能不能了
我前几天给中国的客服发工单她说弄不了，不知道是只有中国的不行吗

**Comment by ChirmyRam** [comment]
国区和美区现在基本都不行了，找一些非简中、英语的冷门地区试一试也许有机会，总之得软磨硬泡。

**Comment by mengguyi** [comment]
thanks
